<?php
// Français translation of GeoCrazy, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:63
$GLOBALS['__l10n']['Location:']='Lieu :';

# _admin.php:68
# _admin.php:72
# settings.php:85
# settings.php:88
$GLOBALS['__l10n']['Add location']='Ajouter un lieu';

# _admin.php:69
# _admin.php:73
# settings.php:86
# settings.php:89
$GLOBALS['__l10n']['Edit location']='Changer le lieu';

# _install.php:30
# settings.php:20
$GLOBALS['__l10n']['Google Maps API key']='Clé Google Maps API';

# _install.php:33
# settings.php:23
# settings.php:75
$GLOBALS['__l10n']['Enable multiple widget']='Mode "widget multiple" pour placer plusieurs fois le même widget';

# _install.php:36
# settings.php:26
$GLOBALS['__l10n']['Blog position']='Localisation du blog';

# _install.php:37
# settings.php:29
$GLOBALS['__l10n']['Blog region']='Région du blog';

# _install.php:38
# settings.php:32
$GLOBALS['__l10n']['Blog placename']='Lieu du blog';

# _widgets.php:28
$GLOBALS['__l10n']['GeoCrazy Map']='Carte GeoCrazy';

# _widgets.php:31
$GLOBALS['__l10n']['Location']='Sur la carte';

# _widgets.php:34
$GLOBALS['__l10n']['Width (in pixels, empty value = 100%):']='Largeur (en pixels, vide = 100%) :';

# _widgets.php:37
$GLOBALS['__l10n']['Height (in pixels):']='Hauteur (en pixels) :';

# _widgets.php:40
$GLOBALS['__l10n']['Zoom (0 = far, 19 = close):']='Zoom (0 = éloigné, 19 = proche) :';

# _widgets.php:63
# _widgets.php:64
$GLOBALS['__l10n']['physical']='relief';

# _widgets.php:65
$GLOBALS['__l10n']['normal']='plan';

# _widgets.php:66
$GLOBALS['__l10n']['satellite']='satellite';

# _widgets.php:67
$GLOBALS['__l10n']['hybrid']='mixte';

# _widgets.php:72
$GLOBALS['__l10n']['ID (If you use several GeoCrazy Map widgets, choose a different ID for each of them):']='ID (Si vous placez plusieurs widgets GeoCrazy, choisissez un ID différent pour chacun) :';

# popup.php:15
# popup.php:23
$GLOBALS['__l10n']['Map your post']='Placez votre billet sur la carte';

# popup.php:19
$GLOBALS['__l10n']['was not found.']='ne peut pas être localisé.';

# popup.php:25
$GLOBALS['__l10n']['Find location']='Rechercher un lieu';

# popup.php:27
$GLOBALS['__l10n']['Go']='OK';

# popup.php:31
$GLOBALS['__l10n']['Remove from map']='Supprimer de la carte';

# popup.php:35
$GLOBALS['__l10n']['Save location']='Enregistrer le lieu';

# settings.php:61
$GLOBALS['__l10n']['Configuration']='Configuration';

# settings.php:64
$GLOBALS['__l10n']['Settings']='Paramètres';

# settings.php:65
$GLOBALS['__l10n']['Google Maps API key:']='clé Google Maps API :';

# settings.php:67
$GLOBALS['__l10n']['Get your Google Maps API key']='Demander votre clé Google Maps API';

# settings.php:71
$GLOBALS['__l10n']['Advanced parameters']='Paramètres avancés';

# settings.php:81
$GLOBALS['__l10n']['Blog localization']='Localisation du blog';

# settings.php:99
$GLOBALS['__l10n']['GeoRSS feed']='Flux GeoRSS';

# settings.php:101
$GLOBALS['__l10n']['If you have already localized some posts of your blog, the RSS (and atom) feeds are now GeoRSS feeds which can be displayed on a map.']='Si vous avez déjà géolocalisé des billets, les flux RSS (ou Atom) sont maintenant des flux GeoRSS qui peuvent être affichés sur une carte.';

# settings.php:105
$GLOBALS['__l10n']['My RSS feed:']='Mon flux RSS :';

# settings.php:106
$GLOBALS['__l10n']['My RSS feed displayed in Google Maps:']='Mon flux RSS affiché dans Google Maps :';

# settings.php:107
$GLOBALS['__l10n']['My RSS feed displayed in Live Maps:']='Mon flux RSS affiché dans Live Maps :';

# settings.php:112
$GLOBALS['__l10n']['Geo sitemap']='Sitemap géographique';

# settings.php:114
$GLOBALS['__l10n']['To help web search engines to index your geolocalised contents, you can submit to them your geo sitemap.']='Pour aider les moteurs de recherche à indexer vos contenus géolocalisé, vous pouvez leur soumettre votre sitemap géographique.';

# settings.php:116
$GLOBALS['__l10n']['My geo sitemap:']='Mon sitemap géographique :';

# settings.php:125
$GLOBALS['__l10n']['About']='A propos';

# settings.php:127
$GLOBALS['__l10n']['GeoCrazy is written by Benjamin Dumas']='GeoCrazy est écrit par Benjamin Dumas';

# settings.php:128
$GLOBALS['__l10n']['For some help, please write a comment on']='Pour toute question, suggestion, remarque, témoignage... veuillez laisser un commentaire sur';

# settings.php:128
$GLOBALS['__l10n']['the support page of GeoCrazy']='la page support de GeoCrazy';

$GLOBALS['__l10n']['Advanced mode']='Mode avancé';

$GLOBALS['__l10n']['Mode:']='Mode :';

$GLOBALS['__l10n']['simple']='simple';

$GLOBALS['__l10n']['advanced']='avancé';

$GLOBALS['__l10n']['In advanced mode, you can use several GeoCrazy widgets.']='Avec le mode avancé, vous pouvez placer plusieurs widgets GeoCrazy.';

$GLOBALS['__l10n']['For some help, please write a comment on ']='Pour toute question, suggestion, remarque, témoignage... veuillez laisser un commentaire sur';

$GLOBALS['__l10n']['Place']='Lieu';

$GLOBALS['__l10n']['Latitude']='Latitude';

$GLOBALS['__l10n']['Longitude']='Longitude';

?>