<?php
// Français translation of GeoCrazy, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:53
$GLOBALS['__l10n']['Location:']='Lieu :';

# _admin.php:60
# _admin.php:64
# settings.php:108
# settings.php:111
$GLOBALS['__l10n']['Add location']='Ajouter un lieu';

# _admin.php:61
# _admin.php:65
# settings.php:109
# settings.php:112
$GLOBALS['__l10n']['Edit location']='Changer le lieu';

# _admin.php:86
$GLOBALS['__l10n']['Override default display']='Paramètres de la carte';

# _admin.php:98
$GLOBALS['__l10n']['Zoom:']='Zoom :';

# _admin.php:123
# _widgets.php:69
# _widgets.php:70
$GLOBALS['__l10n']['physical']='relief';

# _admin.php:124
# _widgets.php:71
$GLOBALS['__l10n']['normal']='plan';

# _admin.php:125
# _widgets.php:72
$GLOBALS['__l10n']['satellite']='satellite';

# _admin.php:126
# _widgets.php:73
$GLOBALS['__l10n']['hybrid']='mixte';

# _admin.php:132
$GLOBALS['__l10n']['Display address:']='Afficher le lieu :';

# _admin.php:133
$GLOBALS['__l10n']['do not display']='Ne pas afficher';

# _admin.php:134
$GLOBALS['__l10n']['display']='Afficher';

# _widgets.php:28
$GLOBALS['__l10n']['GeoCrazy Map']='Carte GeoCrazy';

# _widgets.php:31
$GLOBALS['__l10n']['Object of the map:']='Sujet de la carte';

# _widgets.php:31
# _widgets.php:32
$GLOBALS['__l10n']['post location']='lieu du billet';

# _widgets.php:33
$GLOBALS['__l10n']['blog location (home only)']='lieu du blog (page d\'accueil seulement)';

# _widgets.php:34
$GLOBALS['__l10n']['blog location (all pages)']='lieu du blog (toutes les pages)';

# _widgets.php:37
$GLOBALS['__l10n']['Location']='Carte';

# _widgets.php:40
$GLOBALS['__l10n']['Width (in pixels, empty value = 100%):']='Largeur (en pixels, vide = 100%) :';

# _widgets.php:43
$GLOBALS['__l10n']['Height (in pixels):']='Hauteur (en pixels) :';

# _widgets.php:46
$GLOBALS['__l10n']['Zoom (0 = far, 19 = close):']='Zoom (0 = éloigné, 19 = proche) :';

# _widgets.php:77
$GLOBALS['__l10n']['Display address']='Afficher le lieu';

# _widgets.php:82
$GLOBALS['__l10n']['ID (If you use several GeoCrazy Map widgets, choose a different ID for each of them):']='ID (Si vous placez plusieurs widgets GeoCrazy, choisissez un ID différent pour chacun) :';

# class.gc.location.php:104
$GLOBALS['__l10n']['Blog position']='Localisation du blog';

# class.gc.location.php:110
$GLOBALS['__l10n']['Blog country code']='Code pays du blog';

# class.gc.location.php:116
$GLOBALS['__l10n']['Blog country']='Pays du blog';

# class.gc.location.php:122
$GLOBALS['__l10n']['Blog region']='Région du blog';

# class.gc.location.php:128
$GLOBALS['__l10n']['Blog locality']='Commune du blog';

# popup.php:15
# popup.php:33
$GLOBALS['__l10n']['Map your post']='Placez votre billet sur la carte';

# popup.php:19
$GLOBALS['__l10n']['was not found.']='ne peut pas être localisé.';

# popup.php:20
$GLOBALS['__l10n']['Your location could not be found.']='Votre position n\'a pas été trouvée.';

# popup.php:35
$GLOBALS['__l10n']['Find location']='Rechercher un lieu';

# popup.php:37
$GLOBALS['__l10n']['Go']='OK';

# popup.php:41
$GLOBALS['__l10n']['Remove from map']='Supprimer de la carte';

# popup.php:45
$GLOBALS['__l10n']['Save location']='Enregistrer le lieu';

# settings.php:21
$GLOBALS['__l10n']['Google Maps API key']='Clé Google Maps API';

# settings.php:24
# settings.php:83
$GLOBALS['__l10n']['Enable multiple widget']='Mode "widget multiple" pour placer plusieurs fois le même widget';

# settings.php:27
$GLOBALS['__l10n']['Save address']='Enregistrer l\'adresse';

# settings.php:30
$GLOBALS['__l10n']['Override widget display']='Surcharge des paramètres du widget';

# settings.php:33
$GLOBALS['__l10n']['Default location']='Lieu par défaut';

# settings.php:69
$GLOBALS['__l10n']['Configuration']='Configuration';

# settings.php:72
$GLOBALS['__l10n']['Settings']='Paramètres';

# settings.php:73
$GLOBALS['__l10n']['Google Maps API key:']='clé Google Maps API :';

# settings.php:75
$GLOBALS['__l10n']['Get your Google Maps API key']='Demander votre clé Google Maps API';

# settings.php:79
$GLOBALS['__l10n']['Advanced parameters']='Paramètres avancés';

# settings.php:85
$GLOBALS['__l10n']['Try to save the address of the location (region and locality)']='Enregistrer l\'adresse du lieu';

# settings.php:87
$GLOBALS['__l10n']['Enable override of widget display']='Permettre le paramétrage du widget par billet';

# settings.php:89
$GLOBALS['__l10n']['Default location when adding a location to a post:']='Lieu par défaut lors de l\'ajout d\'un lieu :';

# settings.php:91
$GLOBALS['__l10n']['No default location']='Aucun';

# settings.php:93
$GLOBALS['__l10n']['Blog location']='Lieu du blog';

# settings.php:95
$GLOBALS['__l10n']['Try to locate the author']='Essayer de localiser l\'auteur';

# settings.php:102
$GLOBALS['__l10n']['Blog localization']='Localisation du blog';

# settings.php:126
$GLOBALS['__l10n']['GeoRSS feed']='Flux GeoRSS';

# settings.php:128
$GLOBALS['__l10n']['If you have already localized some posts of your blog, the RSS (and atom) feeds are now GeoRSS feeds which can be displayed on a map.']='Si vous avez déjà géolocalisé des billets, les flux RSS (ou Atom) sont maintenant des flux GeoRSS qui peuvent être affichés sur une carte.';

# settings.php:132
$GLOBALS['__l10n']['My RSS feed:']='Mon flux RSS :';

# settings.php:133
$GLOBALS['__l10n']['My RSS feed displayed in Google Maps:']='Mon flux RSS affiché dans Google Maps :';

# settings.php:134
$GLOBALS['__l10n']['My RSS feed displayed in Live Maps:']='Mon flux RSS affiché dans Live Maps :';

# settings.php:139
$GLOBALS['__l10n']['Geo sitemap']='Sitemap géographique';

# settings.php:141
$GLOBALS['__l10n']['To help web search engines to index your geolocalised contents, you can submit to them your geo sitemap.']='Pour aider les moteurs de recherche à indexer vos contenus géolocalisé, vous pouvez leur soumettre votre sitemap géographique.';

# settings.php:143
$GLOBALS['__l10n']['My geo sitemap:']='Mon sitemap géographique :';

# settings.php:152
$GLOBALS['__l10n']['About']='A propos';

# settings.php:154
$GLOBALS['__l10n']['GeoCrazy is written by Benjamin Dumas']='GeoCrazy est écrit par Benjamin Dumas';

# settings.php:155
$GLOBALS['__l10n']['For some help, please write a comment on']='Pour toute question, suggestion, remarque, témoignage... veuillez laisser un commentaire sur';

# settings.php:155
$GLOBALS['__l10n']['the support page of GeoCrazy']='la page support de GeoCrazy';

$GLOBALS['__l10n']['Default location when adding a location to a post']='Lieu par défaut lors de l\'ajout d\'un lieu';

$GLOBALS['__l10n']['Blog country name']='Nom du pays du blog';

$GLOBALS['__l10n']['post']='billet';

$GLOBALS['__l10n']['bloghomeonly']='blog (page d\'accueil seulement)';

$GLOBALS['__l10n']['blog']='blog (toutes les pages)';

$GLOBALS['__l10n']['Blog placename']='Lieu du blog';

$GLOBALS['__l10n']['Display address under the map']='Afficher l\'adresse sous la carte';

$GLOBALS['__l10n']['Advanced mode']='Mode avancé';

$GLOBALS['__l10n']['Mode:']='Mode :';

$GLOBALS['__l10n']['simple']='simple';

$GLOBALS['__l10n']['advanced']='avancé';

$GLOBALS['__l10n']['In advanced mode, you can use several GeoCrazy widgets.']='Avec le mode avancé, vous pouvez placer plusieurs widgets GeoCrazy.';

$GLOBALS['__l10n']['For some help, please write a comment on ']='Pour toute question, suggestion, remarque, témoignage... veuillez laisser un commentaire sur';

$GLOBALS['__l10n']['Place']='Lieu';

$GLOBALS['__l10n']['Latitude']='Latitude';

$GLOBALS['__l10n']['Longitude']='Longitude';

?>