<?php
// Español translation of GeoCrazy, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:52
$GLOBALS['__l10n']['Location:']='Ubicación:';

# _admin.php:59
# _admin.php:63
# settings.php:126
# settings.php:129
$GLOBALS['__l10n']['Add location']='Añadir ubicación';

# _admin.php:60
# _admin.php:64
# settings.php:127
# settings.php:130
$GLOBALS['__l10n']['Edit location']='Editar ubicación';

# _admin.php:85
$GLOBALS['__l10n']['Override default display']='Enmendar la visualización por defecto';

# _admin.php:88
# _widgets.php:37
$GLOBALS['__l10n']['Title:']='Título:';

# _admin.php:91
$GLOBALS['__l10n']['Width:']='Anchura:';

# _admin.php:94
$GLOBALS['__l10n']['Height:']='Altura:';

# _admin.php:97
$GLOBALS['__l10n']['Zoom:']='Zoom:';

# _admin.php:120
# _widgets.php:69
$GLOBALS['__l10n']['Type:']='Tipo::';

# _admin.php:122
# _widgets.php:69
# _widgets.php:70
$GLOBALS['__l10n']['physical']='relieve';

# _admin.php:123
# _widgets.php:71
$GLOBALS['__l10n']['normal']='mapa';

# _admin.php:124
# _widgets.php:72
$GLOBALS['__l10n']['satellite']='satélite';

# _admin.php:125
# _widgets.php:73
$GLOBALS['__l10n']['hybrid']='mezcla';

# _admin.php:130
$GLOBALS['__l10n']['Display address:']='Exponer la dirección';

# _admin.php:131
$GLOBALS['__l10n']['do not display']='no exponer';

# _admin.php:132
$GLOBALS['__l10n']['display']='exponer';

# _admin.php:138
$GLOBALS['__l10n']['ID:']='ID:';

# _widgets.php:28
$GLOBALS['__l10n']['GeoCrazy Map']='GeoCrazy mapa';

# _widgets.php:31
$GLOBALS['__l10n']['Object of the map:']='Tema de la mapa:';

# _widgets.php:31
# _widgets.php:32
$GLOBALS['__l10n']['post location']='ubicación del artículo';

# _widgets.php:33
$GLOBALS['__l10n']['blog location (home only)']='ubicación del blog (sólo la página frontal)';

# _widgets.php:34
$GLOBALS['__l10n']['blog location (all pages)']='ubicación del blog (todas las páginas)';

# _widgets.php:37
$GLOBALS['__l10n']['Location']='Ubicación';

# _widgets.php:40
$GLOBALS['__l10n']['Width (in pixels, empty value = 100%):']='Anchura (en píxels, no valor = 100%):';

# _widgets.php:43
$GLOBALS['__l10n']['Height (in pixels):']='Altura (en píxels)';

# _widgets.php:46
$GLOBALS['__l10n']['Zoom (0 = far, 19 = close):']='Zoom (0 = lejos, 19 = cerca)';

# _widgets.php:77
$GLOBALS['__l10n']['Display address']='Fijar la dirección';

# _widgets.php:82
$GLOBALS['__l10n']['ID (If you use several GeoCrazy Map widgets, choose a different ID for each of them):']='ID (si utiliza varios GeoCrazy mapas, elege un ID diferente para cada widget):';

# class.gc.location.php:108
$GLOBALS['__l10n']['Blog position']='Ubicación del blog';

# class.gc.location.php:114
$GLOBALS['__l10n']['Blog country code']='Código del país del blog';

# class.gc.location.php:120
$GLOBALS['__l10n']['Blog country']='País del blog';

# class.gc.location.php:126
$GLOBALS['__l10n']['Blog region']='Región del blog';

# class.gc.location.php:132
$GLOBALS['__l10n']['Blog locality']='Localidad del blog';

# popup.php:15
# popup.php:32
$GLOBALS['__l10n']['Map your post']='Sitúa el artículo en un mapa';

# popup.php:18
$GLOBALS['__l10n']['was not found.']='no ha estado encontrado.';

# popup.php:19
$GLOBALS['__l10n']['Your location could not be found.']='Su ubicación no ha podido estar encontrado.';

# popup.php:34
$GLOBALS['__l10n']['Find location']='Buscar ubicación';

# popup.php:36
$GLOBALS['__l10n']['Go']='Ir';

# popup.php:40
$GLOBALS['__l10n']['Remove from map']='Eliminar del mapa';

# popup.php:44
$GLOBALS['__l10n']['Save location']='Guardar ubicación';

# popup.php:45
$GLOBALS['__l10n']['Cancel']='Cancelar';

# settings.php:22
$GLOBALS['__l10n']['Map provider']='Proveedor de mapas';

# settings.php:25
$GLOBALS['__l10n']['Google Maps API key']='Clave de API de Google Maps';

# settings.php:28
$GLOBALS['__l10n']['Yahoo Maps API key']='Clave de API de Yahoo Maps';

# settings.php:31
# settings.php:90
$GLOBALS['__l10n']['Enable multiple widget']='Permitir varios widgets';

# settings.php:34
$GLOBALS['__l10n']['Save address']='Guardar la dirección';

# settings.php:37
$GLOBALS['__l10n']['Override widget display']='Enmendar la visualización por defecto del widget';

# settings.php:40
$GLOBALS['__l10n']['Default location']='Ubicación por defecto';

# settings.php:71
$GLOBALS['__l10n']['Settings have been successfully updated.']='La configuración ha estado cambiado bien.';

# settings.php:76
$GLOBALS['__l10n']['Configuration']='Configuración';

# settings.php:79
$GLOBALS['__l10n']['Settings']='Configuración';

# settings.php:80
$GLOBALS['__l10n']['Google Maps API key:']='Clave de API de Google Maps:';

# settings.php:82
$GLOBALS['__l10n']['Get your Google Maps API key']='Consigue su clave de API de Google Maps';

# settings.php:86
$GLOBALS['__l10n']['Advanced parameters']='Configuración adelantada';

# settings.php:92
$GLOBALS['__l10n']['Try to save the address of the location (region and locality)']='Tratar de registrar la dirección (región y localidad)';

# settings.php:94
$GLOBALS['__l10n']['Enable override of widget display']='Permitir de enmendar la visualización por defecto del widget';

# settings.php:96
$GLOBALS['__l10n']['Default location when adding a location to a post:']='Ubicación por defecto:';

# settings.php:98
$GLOBALS['__l10n']['No default location']='No ubicación por defecto';

# settings.php:100
$GLOBALS['__l10n']['Blog location']='Ubicación del blog';

# settings.php:102
$GLOBALS['__l10n']['Try to locate the author']='Tratar de localizar el autor';

# settings.php:106
$GLOBALS['__l10n']['Map provider:']='Proveedor de mapas:';

# settings.php:107
$GLOBALS['__l10n']['Google']='Google';

# settings.php:108
$GLOBALS['__l10n']['OpenLayers']='OpenLayers';

# settings.php:109
$GLOBALS['__l10n']['Yahoo']='Yahoo';

# settings.php:112
$GLOBALS['__l10n']['Yahoo Maps API key:']='Clave de API de Yahoo Maps';

# settings.php:114
$GLOBALS['__l10n']['Get your Yahoo Maps API key']='Consigue su clave de API de Yahoo Maps';

# settings.php:116
# settings.php:138
$GLOBALS['__l10n']['Save']='Guardar';

# settings.php:120
$GLOBALS['__l10n']['Blog localization']='Ubicación del blog';

# settings.php:144
$GLOBALS['__l10n']['GeoRSS feed']='Fuente GeoRSS';

# settings.php:146
$GLOBALS['__l10n']['If you have already localized some posts of your blog, the RSS (and atom) feeds are now GeoRSS feeds which can be displayed on a map.']='Si ya ha localizado unos articulos del blog, el fuente RSS (y atom) son GeoRSS, cuales pueden ser visualizado en un mapa.';

# settings.php:150
$GLOBALS['__l10n']['My RSS feed:']='Mi fuente RSS:';

# settings.php:151
$GLOBALS['__l10n']['My RSS feed displayed in Google Maps:']='Mi fuente RSS visualizado en Google Maps:';

# settings.php:152
$GLOBALS['__l10n']['My RSS feed displayed in Live Maps:']='Mi fuente RSS visualizado en Live Maps:';

# settings.php:157
$GLOBALS['__l10n']['Geo sitemap']='Geo sitemap';

# settings.php:159
$GLOBALS['__l10n']['To help web search engines to index your geolocalised contents, you can submit to them your geo sitemap.']='Para ayudar motores de búsqueda a indexar sus articulos geoetiquetados, puede someter su geo sitemap.';

# settings.php:161
$GLOBALS['__l10n']['My geo sitemap:']='Mi geo sitemap:';

# settings.php:166
$GLOBALS['__l10n']['Documentation']='Documentación';

# settings.php:170
$GLOBALS['__l10n']['About']='Acerca de...';

# settings.php:172
$GLOBALS['__l10n']['GeoCrazy is written by Benjamin Dumas']='Geocrazy esta escrito por Benjamin Dumas';

# settings.php:173
$GLOBALS['__l10n']['For some help, please write a comment on']='Si necesita ayuda, escribe un comentario en';

# settings.php:173
$GLOBALS['__l10n']['the support page of GeoCrazy']='la página web de GeoCrazy';

$GLOBALS['__l10n']['Default location when adding a location to a post']='Ubicación por defecto al añadir un ubicación a un billete';

$GLOBALS['__l10n']['post']='billete';

?>