<?php
// Español translation of GeoCrazy, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:53
$GLOBALS['__l10n']['Location:']='Ubicación:';

# _admin.php:60
# _admin.php:64
# settings.php:108
# settings.php:111
$GLOBALS['__l10n']['Add location']='Añadir ubicación';

# _admin.php:61
# _admin.php:65
# settings.php:109
# settings.php:112
$GLOBALS['__l10n']['Edit location']='Editar ubicación';

# _admin.php:86
$GLOBALS['__l10n']['Override default display']='Enmendar la visualización por defecto';

# _admin.php:89
# _widgets.php:37
$GLOBALS['__l10n']['Title:']='Título:';

# _admin.php:92
$GLOBALS['__l10n']['Width:']='Anchura:';

# _admin.php:95
$GLOBALS['__l10n']['Height:']='Altura:';

# _admin.php:98
$GLOBALS['__l10n']['Zoom:']='Zoom:';

# _admin.php:121
# _widgets.php:69
$GLOBALS['__l10n']['Type:']='Tipo::';

# _admin.php:123
# _widgets.php:69
# _widgets.php:70
$GLOBALS['__l10n']['physical']='relieve';

# _admin.php:124
# _widgets.php:71
$GLOBALS['__l10n']['normal']='mapa';

# _admin.php:125
# _widgets.php:72
$GLOBALS['__l10n']['satellite']='satélite';

# _admin.php:126
# _widgets.php:73
$GLOBALS['__l10n']['hybrid']='mezcla';

# _admin.php:132
$GLOBALS['__l10n']['Display address:']='Exponer la dirección';

# _admin.php:133
$GLOBALS['__l10n']['do not display']='no exponer';

# _admin.php:134
$GLOBALS['__l10n']['display']='exponer';

# _widgets.php:28
$GLOBALS['__l10n']['GeoCrazy Map']='GeoCrazy mapa';

# _widgets.php:31
$GLOBALS['__l10n']['Object of the map:']='Tema de la mapa:';

# _widgets.php:31
# _widgets.php:32
$GLOBALS['__l10n']['post location']='ubicación del artículo';

# _widgets.php:33
$GLOBALS['__l10n']['blog location (home only)']='ubicación del blog (sólo la página frontal)';

# _widgets.php:34
$GLOBALS['__l10n']['blog location (all pages)']='ubicación del blog (todas las páginas)';

# _widgets.php:37
$GLOBALS['__l10n']['Location']='Ubicación';

# popup.php:42
$GLOBALS['__l10n']['Remove from map']='Eliminar del mapa';

?>