<?php
// Español translation of GeoCrazy, a plugin for dotclear
// This file is generated by LangOmatic, a plugin for Dotclear

# _admin.php:53
# _admin_backup.php:67
$GLOBALS['__l10n']['Location:']='Ubicación:';

# _admin.php:60
# _admin.php:64
# _admin_backup.php:90
# _admin_backup.php:94
# settings.php:96
# settings.php:99
# settings_backup.php:141
# settings_backup.php:144
$GLOBALS['__l10n']['Add location']='Añadir ubicación';

# _admin.php:61
# _admin.php:65
# _admin_backup.php:91
# _admin_backup.php:95
# settings.php:97
# settings.php:100
# settings_backup.php:142
# settings_backup.php:145
$GLOBALS['__l10n']['Edit location']='Editar ubicación';

# _admin.php:86
# _admin_backup.php:129
$GLOBALS['__l10n']['Override default display']='Enmendar la visualización por defecto';

# _admin.php:89
# _admin_backup.php:132
# _widgets.php:37
$GLOBALS['__l10n']['Title:']='Título:';

# _admin.php:92
# _admin_backup.php:135
$GLOBALS['__l10n']['Width:']='Anchura:';

# _admin.php:95
# _admin_backup.php:138
$GLOBALS['__l10n']['Height:']='Altura:';

# _admin.php:98
# _admin_backup.php:141
$GLOBALS['__l10n']['Zoom:']='Zoom:';

# _admin.php:121
# _admin_backup.php:164
# _widgets.php:69
$GLOBALS['__l10n']['Type:']='Tipo::';

# _admin.php:123
# _admin_backup.php:166
# _widgets.php:69
# _widgets.php:70
$GLOBALS['__l10n']['physical']='relieve';

# _admin.php:124
# _admin_backup.php:167
# _widgets.php:71
$GLOBALS['__l10n']['normal']='mapa';

# _admin.php:125
# _admin_backup.php:168
# _widgets.php:72
$GLOBALS['__l10n']['satellite']='satélite';

# _admin.php:126
# _admin_backup.php:169
# _widgets.php:73
$GLOBALS['__l10n']['hybrid']='mezcla';

# _admin.php:132
# _admin_backup.php:180
$GLOBALS['__l10n']['Display address:']='Exponer la dirección';

# _admin.php:133
# _admin_backup.php:181
$GLOBALS['__l10n']['do not display']='no exponer';

# _admin.php:134
# _admin_backup.php:182
$GLOBALS['__l10n']['display']='exponer';

# _widgets.php:28
$GLOBALS['__l10n']['GeoCrazy Map']='GeoCrazy mapa';

# _widgets.php:31
$GLOBALS['__l10n']['Object of the map:']='Tema de la mapa:';

# _widgets.php:31
# _widgets.php:32
$GLOBALS['__l10n']['post location']='ubicación del artículo';

# _widgets.php:33
$GLOBALS['__l10n']['blog location (home only)']='ubicación del blog (sólo la página frontal)';

# _widgets.php:34
$GLOBALS['__l10n']['blog location (all pages)']='ubicación del blog (todas las páginas)';

# _widgets.php:37
$GLOBALS['__l10n']['Location']='Ubicación';

# popup.php:33
$GLOBALS['__l10n']['Remove from map']='Eliminar del mapa';

?>